language: python
python:
 - "3.5"
install:
  - python -m pip install --upgrade pip
before_script:
  - git clone https://github.com/Tirth-Patel903/Tirth-Patel903567
  - cd Tirth-Patel903567
  - git checkout main
env:
  - PYTHONPATH=$PYTHONPATH: https://github.com/Tirth-Patel903/Tirth-Patel903567
script:
  - ls
  - export PYTHONPATH=$PYTHONPATH:$PW
  - python -m unittest TestTriangle